tune gostyle dir and update codec
moladb/SetGolangClientProxy pull request #1
Opened 2017-08-11 13:22 UTC by crafet

@weiwei04 @jacksome 
pls review

2017-08-11 14:59 UTC, weiwei04 requested changes

2017-08-11 14:59 UTC, weiwei04 commented on main.go
> +package main
unessary

2017-08-11 14:59 UTC, weiwei04 commented on snippet/build_package.go
> +func TestBuildPackage() {
you can mv func TestBuildPackage into a new file build_package_test.go and use go Test/Example to test/demo your function.

https://golang.org/pkg/testing/

https://blog.golang.org/examples

2017-08-12 05:55 UTC, crafet commented
@weiwei04  thx
Let me close this thread and will submit a new PR soon

2017-08-12 05:55 UTC, closed without merging